name: flutter_web.examples.box_plot

dependencies:
  flutter_web: any

dev_dependencies:
  build_runner: ^1.2.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.4.0
  test: ^1.5.3

dependency_overrides:
  flutter_web:
    path: ../../packages/flutter_web
  flutter_web_ui:
    path: ../../packages/flutter_web_ui
